name: Manuell Workflow

on:
  workflow_dispatch:   # <-- här anges att workflow kan startas manuellt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Körs när du själv startar workflow manuellt!"
